openapi: 3.0.0
info:
  title: API de Resultados de Fútbol
  description: Una API para obtener resultados de fútbol y estadísticas de la liga española.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: Servidor de desarrollo
paths:
  /equipos:
    get:
      summary: Lista todos los equipos
      responses:
        '200':
          description: Una lista de equipos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Equipo'
    post:
      summary: Crea un nuevo equipo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Equipo'
      responses:
        '201':
          description: Equipo creado exitosamente
        '400':
          description: Datos inválidos proporcionados
  /equipos/{id}:
    get:
      summary: Obtiene los detalles de un equipo específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de un equipo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipo'
        '404':
          description: Equipo no encontrado
  /partidos:
    get:
      summary: Lista todos los partidos
      responses:
        '200':
          description: Una lista de partidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Partido'
    post:
      summary: Programa un nuevo partido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partido'
      responses:
        '201':
          description: Partido creado exitosamente
        '400':
          description: Datos inválidos proporcionados
  /partidos/{id}/resultado:
    get:
      summary: Obtiene el resultado de un partido específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Resultado del partido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultado'
    put:
      summary: Actualiza el resultado de un partido específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resultado'
      responses:
        '200':
          description: Resultado actualizado
        '400':
          description: Datos inválidos proporcionados
        '404':
          description: Partido no encontrado
  /estadisticas:
    get:
      summary: Obtiene estadísticas generales de la liga
      responses:
        '200':
          description: Estadísticas generales de la liga
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstadisticasGenerales'
  /estadisticas/equipos/{id}:
    get:
      summary: Obtiene estadísticas específicas de un equipo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Estadísticas específicas de un equipo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstadisticasEquipo'
        '404':
          description: Equipo no encontrado
  /estadisticas/partidos/{id}:
    get:
      summary: Obtiene estadísticas específicas de un partido
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Estadísticas específicas de un partido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstadisticasPartido'
        '404':
          description: Partido no encontrado
  /estadisticas/externas:
    get:
      summary: Obtiene estadísticas desde una API externa
      parameters:
        - name: apiKey
          in: query
          required: true
          schema:
            type: string
        - name: tipoEstadistica
          in: query
          required: true
          schema:
            type: string
            enum: [general, equipo, partido]
      responses:
        '200':
          description: Estadísticas obtenidas de la API externa
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          description: API Key no válida o faltante
        '403':
          description: Acceso a la API externa denegado
        '500':
          description: Error al obtener datos de la API externa
components:
  schemas:
    Equipo:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        estadio:
          type: string
    Partido:
      type: object
      properties:
        id:
          type: integer
        equipoLocal:
          type: string
        equipoVisitante:
          type: string
        fecha:
          type: string
          format: date-time
    Resultado:
      type: object
      properties:
        golesLocal:
          type: integer
        golesVisitante:
          type: integer
    EstadisticasGenerales:
      type: object
      properties:
        partidosJugados:
          type: integer
        golesTotales:
          type: integer
        tarjetasRojas:
          type: integer
        tarjetasAmarillas:
          type: integer
    EstadisticasEquipo:
      type: object
      properties:
        partidosGanados:
          type: integer
        partidosPerdidos:
          type: integer
        golesAFavor:
          type: integer
        golesEnContra:
          type: integer
    EstadisticasPartido:
      type: object
      properties:
        posesionEquipoLocal:
          type: integer
        posesionEquipoVisitante:
          type: integer
        tirosAlArcoLocal:
          type: integer
        tirosAlArcoVisitante:
          type: integer
